remote_theme: joeeasterly/pages_theme_joeeasterly
sass:
  style: expanded
  # Where you keep your scss files
  sass_dir: _sass
- name: Sass Build
  uses: gha-utilities/sass-build@v0.4.9

personal-name: Joe Easterly
occupation: Digital Scholarship Librarian
description: Digital Scholarship Librarian, University of Rochester
institution: University of Rochester
title: Joe Easterly