remote_theme: joeeasterly/pages_theme_joeeasterly@v0.2.0
sass:
  style: expanded
  # Where you keep your scss files
  sass_dir: _sass

layout: "default"
personal-name: Joe Easterly
occupation: Digital Scholarship Librarian
description: Digital Scholarship Librarian, University of Rochester
institution: University of Rochester
title: Joe Easterly