personal-name: Joe Easterly
occupation: Digital Scholarship Librarian
institution: University of Rochester
title: Joe Easterly
sass:
  # style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/