personal-name: Joe Easterly
occupation: Digital Scholarship Librarian
institution: University of Rochester
title: Joe Easterly
ignore_theme_config: TRUE
sass:
  style: expanded
  # Where you keep your scss files
  sass_dir: _sass